server:
  port: 8088

spring:
  profiles:
    # SPRING_PROFILES_ACTIVE=dev
    active: dev
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/group_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

#  sql:
#    init:
#      schema-locations: classpath:db/mysql/init-schema.sql
#      data-locations: classpath:db/mysql/init-data.sql

logging:
  file:
    name: logs/springboot.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
