server:
  port: 8088

spring:
  profiles:
    # SPRING_PROFILES_ACTIVE=dev
    active: dev
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/group_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

#  sql:
#    init:
#      schema-locations: classpath:db/mysql/init-schema.sql
#      data-locations: classpath:db/mysql/init-data.sql

logging:
  file:
    name: logs/springboot.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.khm.group.center
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
