version: "3.8"

services:
  group_center:
    image: group_center
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 15090:15090
    networks:
      group-center-network:
        aliases:
          - GROUP_CENTER_URL
    restart: always
    container_name: GroupCenterJdk21
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    healthcheck:
      test: "/bin/netstat -anpt|grep 15090"
      interval: 10s
      start_period: 30s
      timeout: 3s
      retries: 1
    volumes:
      - ./Config:/usr/local/group-center/Config
      - ./src/main/resources/application-docker.yml:/usr/local/group-center/application.yml
      - ./Data/Log:/usr/local/group-center/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/group_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  db:
    image: mysql:9
    ports:
      - 3306:3306
    networks:
      group-center-network:
        aliases:
          - MYSQL_URL
    restart: always
    container_name: GroupCenterMySQL
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h127.0.0.1 -u root -p123456" ]
      interval: 5s
      start_period: 5s
      timeout: 2s
      retries: 10
    volumes:
      - ./Data/Db/MySQL:/var/lib/mysql
    environment:
      MYSQL_DATABASE: group_center
      MYSQL_ROOT_PASSWORD: 123456

networks:
  group-center-network:
    driver: bridge
