services:
  core:
    image: registry.cn-shanghai.aliyuncs.com/a645162/group-center:latest
    # image: a645162/group-center:latest
    # image: group_center
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 15090:15090
      - 15092:15092
    networks:
      group-center-network:
        aliases:
          - GROUP_CENTER_URL
    restart: always
    # container_name: GroupCenterJdk
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./Config:/usr/local/group-center/Config
      - ./Cache:/usr/local/group-center/Cache
      # - ./src/main/resources/application-docker.yml:/usr/local/group-center/application.yml
      - ./Data/Log:/usr/local/group-center/logs
    environment:
      SPRING_DATASOURCE_HOST: db:3306
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  # Here should be the same as SPRING_DATASOURCE_HOST
  db:
    image: mysql:9
    ports:
      - 15096:3306
    networks:
      group-center-network:
        aliases:
          - MYSQL_URL
    restart: always
    # container_name: GroupCenterMySQL
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h127.0.0.1 -u root -p123456" ]
      interval: 5s
      start_period: 5s
      timeout: 2s
      retries: 10
    volumes:
      - ./Data/Db/MySQL:/var/lib/mysql
      - ./Data/Db/Backup:/usr/local/backup
    environment:
      MYSQL_DATABASE: group_center
      MYSQL_ROOT_PASSWORD: 123456

networks:
  group-center-network:
    driver: bridge
