services:
  db:
    image: mysql:9
    ports:
      - 3306:3306
    networks: bridge
    restart: always
    container_name: GroupCenterMySQLSingle
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h127.0.0.1 -u root -p123456" ]
      interval: 5s
      start_period: 5s
      timeout: 2s
      retries: 10
    environment:
      MYSQL_DATABASE: group_center
      MYSQL_ROOT_PASSWORD: 123456
