# https://hub.docker.com/_/openjdk/tags
# FROM openjdk:26-oraclelinux9

# https://graalvm.java.net.cn/latest/getting-started/container-images/
# https://github.com/graalvm/container/pkgs/container/jdk-community/
FROM ghcr.io/graalvm/jdk-community:24

# MAINTAINER Haomin Kong
LABEL maintainer="Haomin Kong"

ENV BASE_PATH="/usr/local/group-center"
ENV RUN_IN_DOCKER=True

ENV PACKAGE_MANAGER="microdnf"

WORKDIR "$BASE_PATH"

# Upgrade all packages to the latest version
RUN    $PACKAGE_MANAGER update -y \
    && $PACKAGE_MANAGER clean all

# Install Software
RUN    $PACKAGE_MANAGER install -y git python3 python3-pip bash tzdata net-tools findutils \
    && $PACKAGE_MANAGER clean all

# Set the timezone
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone

ENTRYPOINT ["python3", "/usr/local/group-center/build.py", "--clean-cache"]
